spring.application.name=notification-service
server.port=8084

# Spring Cloud Stream / RabbitMQ
spring.cloud.stream.defaultBinder=rabbit
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Event service
spring.cloud.stream.bindings.onEventCreated-in-0.destination=event.created
spring.cloud.stream.bindings.onEventUpdated-in-0.destination=event.updated
spring.cloud.stream.bindings.onEventCancelled-in-0.destination=event.cancelled

# Payment service
spring.cloud.stream.bindings.onPaymentProcessed-in-0.destination=payment.processed
spring.cloud.stream.bindings.onPaymentFailed-in-0.destination=payment.failed

spring.cloud.stream.bindings.*.group=notification-service
