version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_billetterie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billetteriedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_billetterie
    ports:
      - "5672:5672"
      - "15672:15672"

  billetterie-service:
    build:
      context: ./billetterie-service
    container_name: billetterie_service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/billetteriedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq

volumes:
  postgres_data:
