# --- Configuration de la Base de Données ---
# On se connecte à localhost car le code tourne sur ton Mac
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
# Ces identifiants doivent être identiques à ceux du docker-compose.yml
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuration JPA (Hibernate) ---
# update = crée les tables si elles n'existent pas, les modifie si besoin
spring.jpa.hibernate.ddl-auto=update
# Affiche le SQL dans la console (indispensable pour apprendre !)
spring.jpa.show-sql=true
# Rend le SQL plus lisible
spring.jpa.properties.hibernate.format_sql=true
# Utilise le dialecte PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect